# Generated by Django 5.2.4 on 2025-07-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addTask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtask',
            old_name='is_boolean',
            new_name='is_completed',
        ),
    ]
